version: '3.8'

services:
  builder:
    build:
      context: .
      target: builder
    volumes:
      - ./build:/build/build
      - ./logs:/build/logs
    
  tester:
    build:
      context: .
      target: tester
    depends_on:
      - builder
    privileged: true  # Required for QEMU
    volumes:
      - ./logs:/test/logs
      - ./build:/test/build
    environment:
      - DEPLOY_ENV=test 